version: "3.3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  tests:
    image: "alpine:latest"
    volumes:
      - ./fixtures:/fixtures
      - ./bin/generator:/generator
      - ./bin/redis-dump-go:/redis-dump-go
    depends_on:
      - "redis"
    entrypoint: ["/fixtures/acceptance-tests.sh"]