version: "3.3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  tests:
    image: "alpine:latest"
    volumes:
      - ./acceptance-tests:/acceptance-tests
      - ./bin/generator:/generator
      - ./bin/redis-dump-go:/redis-dump-go
    depends_on:
      - "redis"
    working_dir: /acceptance-tests
    entrypoint: ["/acceptance-tests/entrypoint.sh"]